apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-odf-ssl-certificates
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
    app.kubernetes.io/component: placement-binding
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "3"
placementRef:
  name: placement-odf-ssl-certificates
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-odf-ssl-certificate-management
  kind: Policy
  apiGroup: policy.open-cluster-management.io
